### ISSUE TITLE
Implement shift cipher

### ISSUE THREAD

**Issue by TerryThibault** [DefNotProBro/cipher_bruteforce#2]
Nick,

Please implement the shift cipher functions with the following signatures:

std::string shift_cipher_encrypt(std::string plaintext, int shift);
std::string shift_cipher_decrypt(std::string ciphertext, int shift);

**Comment by nicolasiscoding** [comment]
Addressed in https://github.com/DefNotProBro/cipher_bruteforce/pull/14
